# Generated by Django 3.1.7 on 2021-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('EC2', models.IntegerField()),
                ('RDS', models.IntegerField()),
            ],
        ),
    ]
